### ISSUE TITLE
Client unit tests not working

### ISSUE THREAD

**Issue by nilnullzip** [Sanjo/meteor-jasmine#139] opened 2015-01-30 07:51 UTC
I'm running the meteor todos example with velocity. I add the Jasmine supplied client integration and unit test sample code using the "add jasmine client tests" buttons in the testing side bar (exposed by the dot in the upper right.) The client integration test runs and I get a nice green dot for it in the sidebar. But the client unit test indicates "loading" and shows a blue dot. No tests fail. It's just that the unit tests are not being run.

I see that the sample tests have indeed been included in the tests/jasmin/client/unit and integration directories. Investigation using the browser debugger shows that the integration test code was loaded into the browser, but unit test code was not. I'm running meteor 1.0.3.1 and sanjo:jasmine@0.11.0.

Any ideas?

**Comment by Sanjo** [comment] 2015-01-30 11:34
Have a look in the `.meteor/local/log/jasmine-client-unit.log` file. Maybe an error is logged there.
The client unit tests should open in a new Google Chrome window.

**Comment by Sikwan** [comment] 2015-01-30 13:19
Looks like the same issue as this one : https://github.com/Sanjo/meteor-jasmine/issues/112

Which for me is only hapenning on using PhantomJS.

**Comment by Sanjo** [comment] 2015-01-30 13:53
Ok. I make fixing this issue a high priority. I will try to fix it on the weekend.

**Comment by nilnullzip** [comment] 2015-01-30 16:50
In my case, only the client unit test is not working. The other three cases do work.

The Chrome window does not open up for me. This is an excerpt from the log file, which does seem to be indicating a problem:

<pre>
[33mWARN [web-server]: [39m404: /font/OpenSans-Regular-webfont.woff
[33mWARN [web-server]: [39m404: /img/logo-todos.svg
[33mWARN [web-server]: [39m404: /font/OpenSans-Regular-webfont.ttf
[33mWARN [web-server]: [39m404: /icon/todos.woff?5w3um4
[33mWARN [web-server]: [39m404: /icon/todos.ttf?5w3um4
Chrome 40.0.2214 (Mac OS X 10.10.1): Executed 0 of 0[32m SUCCESS[39m (0 secs / 0 secs)
[33mWARN [web-server]: [39m404: /font/OpenSans-Light-webfont.woff
[33mWARN [web-server]: [39m404: /font/OpenSans-Light-webfont.ttf
[1A[2K[31mChrome 40.0.2214 (Mac OS X 10.10.1) ERROR[39m
  Uncaught TypeError: Cannot read property 'release' of null
  at /Users/juan/Temp/programming/meteor/todos/.meteor/local/build/programs/web.browser/app/client/templates/app-body.js:42
Chrome 40.0.2214 (Mac OS X 10.10.1): Executed 0 of 0[31m ERROR[39m (0 secs / 0 secs)
[1A[2KChrome 40.0.2214 (Mac OS X 10.10.1): Executed 0 of 0[31m ERROR[39m (0.995 secs / 0 secs)
</pre>

This is an excerpt from the source file referenced:

<pre>
emplate.appBody.rendered = function() {
  this.find('#content-container')._uihooks = {
    insertElement: function(node, next) {
      $(node)
        .hide()
        .insertBefore(next)
        .fadeIn(function () {
          listFadeInHold.release();
        });
    },
    removeElement: function(node) {
      $(node).fadeOut(function() {
        $(this).remove();
      });
    }
  };
};
</pre>

It would appear that listFadeInHold.release does not exist? Thanks! -Juan

**Comment by nilnullzip** [comment] 2015-01-30 17:19
Hmm, it would appear that the log files were stale.

After deleting all the log files and rerunning, NO jasmine-client-unit.log file is created. Chrome still does not open. The only log files generated are jasmine-server-unit.log, jasmine-server-integration.log, and mocha.log. All three have the same content:

<pre>
[velocity-mirror] Mirror is initializing...
LISTENING
[velocity-mirror] Mirror is ready.
</pre>

Here is the transcript from the console. Note that I had to refresh the web page for it to run the client tests.

<pre>
4pi-3:todos juan$ meteor
[[[[[ ~/Temp/programming/meteor/todos ]]]]]   

=> Started proxy.                             
=> Started MongoDB.                           
=> Started your app.                          

=> App running at: http://localhost:3000/
W20150130-09:15:37.161(-8)? (STDERR) connections property is deprecated. Use getConnections() method
W20150130-09:15:37.343(-8)? (STDERR) [sanjo:jasmine]: The file "/Users/juan/Temp/programming/meteor/todos/mobile-config.js" has syntax errors. [ReferenceError: App is not defined]
I20150130-09:15:37.380(-8)? ConsoleReporter is deprecated and will be removed in a future version.Started
I20150130-09:15:37.455(-8)? ....
I20150130-09:15:37.455(-8)? 
I20150130-09:15:37.455(-8)? 4 specs, 0 failures
I20150130-09:15:37.455(-8)? Finished in 0.075 seconds
I20150130-09:15:40.672(-8)? ConsoleReporter is deprecated and will be removed in a future version.Started
I20150130-09:15:40.712(-8)? .....
I20150130-09:15:40.713(-8)? 
I20150130-09:15:40.713(-8)? 5 specs, 0 failures
I20150130-09:15:40.713(-8)? Finished in 0.041 seconds
I20150130-09:15:44.714(-8)? ConsoleReporter is deprecated and will be removed in a future version.Started
I20150130-09:15:44.758(-8)? .....
I20150130-09:15:44.758(-8)? 
I20150130-09:15:44.758(-8)? 5 specs, 0 failures
I20150130-09:15:44.758(-8)? Finished in 0.044 seconds
 </pre>

**Comment by nilnullzip** [comment] 2015-01-31 05:04
It seems to have something to do with that chrome Karma window that pops up.

1) I found that if I quit that Chrome window altogether that my system seems to get wedged in a way that subsequent restarts of Meteor won't pop up Chrome. I can quit Meteor and close the localhost:3000 window and restart, but it doesn't help. No Chrome window. Then I reboot the system and it works again. Strange.

2) I find that if I quit out of Meteor and restart, that the client side tests are stuck loading. I am leaving the Karma window open. If I reload the localhost:3000 window then the integration test succeeds but the unit test is still stuck loading. But then if I click the debug button in the Karma window to open up the debug tab, then the loading unit test completes and succeeds.

So in my case, all the bad behavior seems to related to that Chrome Karma window. I am running on a MacBook with the latest OSX release, Yosemite. Everything up to date.

**Comment by Sanjo** [comment] 2015-02-01 01:11
I will release a new version soon that has a fix for the client unit mode. I hope that fixes your issue.
The expected behavior is:

* The Karma Chrome window opens shortly after the Meteor app is started
* The Karma Chrome window closes shortly after the Meteor app was terminated
* When client unit tests or client files change, Karma reruns the tests and reports the results to Velocity (displayed in the html-reporter).

**Comment by Sanjo** [comment] 2015-02-01 01:51
Can you please try https://github.com/Sanjo/meteor-jasmine/releases/tag/0.12.0 and report back if you have still issues with this.

**Comment by nilnullzip** [comment] 2015-02-01 03:06
I think perhaps a little better. I installed using

> meteor add sanjo:jasmine@0.12.0

In addition to the update jasmine, it installed Karma 1.4.0.

Behavior 2 above seems better. After restarting meteor both client tests show loading. I then reload the localhost:3000 page and the tests run. Is the requirement to reload the page under those circumstances expected?

Behavior 1 above still broken. For the first three times I quit Chrome while meteor is running, a new Chrome is automatically started with the karma window. But on the fourth time no Chrome restart. Quitting Meteor and restarting it does not bring up the Chrome/karma window. At this point my system is wedged and I can't seem to get Jasmine to open that karma window. I try restarting meteor and also chrome. But no Karma window.

**Comment by Sanjo** [comment] 2015-02-01 03:45
Ok. I could reproduce the issue. The core issue is that the Karma process does not terminate when the app is terminated. I will look into this issue.

When you close the Karma Chrome window, for Karma this is a crash. After three crashes it gives up spawning a new chrome window. Normally you should not close this window manually. This windows must stay open in the background to run the client unit tests.

If it (currently) doesn't close when you terminate your app, you should kill all node processes (I assume no other node programs are running). This will terminate Karma and the Chrome window properly.

**Comment by nilnullzip** [comment] 2015-02-01 03:53
Thanks for the info! I will make sure not to kill Chrome.

I am also having another problem. I am changing the integration test by inserting this extra expect:

>  it("should be able to play a Song", function() {
>     expect(true).toEqual(false);

I find that if I change the false to true back and forth several times, the tests become somehow stale and Jasmine reports success when it should report fail and fail when it should report success. I haven't completely figured out the pattern by which to clear the stale behavior. I've tried restarting meteor, deleting packages/tests-proxy/, and reloading the page. Sometimes I can get it to display the correct result, but I haven't been able to figure out a reproducible sequence.

Any ideas? Thanks! -Juan

**Comment by Sanjo** [comment] 2015-02-01 05:29
The Karma process is now correctly terminated when you terminate your app (in 0.12.1).
Let's start a new issue for the issue https://github.com/Sanjo/meteor-jasmine/issues/139#issuecomment-72350203.

Thank you for your valuable feedback.

**Comment by nilnullzip** [comment] 2015-02-01 06:06
I posted a new issue for the integration tests and also added a bit more info. Thanks!

**Comment by think01** [comment] 2015-02-06 11:56
To anyone interested, I have this same issue. I'm using latest release available (sanjo:jasmine 0.12.1) on Chromium/Ubuntu 14.04. I added the example tests clicking on the buttons in the Velocity reporter window: server tests work but client tests (both unit and integration) get stuck showing the blue dot and the "loading" text. When opening the app no other windows are open.

After a bit digging it appeared the problem is the browser (Chromium and not Chrome), since in `.meteor/local/log/jasmine-client-unit.log` it says: 
```
ESC[31mERROR [launcher]: ESC[39mCannot start Chrome
Can not find the binary google-chrome
Please set env variable CHROME_BIN
```
So I set CHROME_BIN to my Chromium executable. Now unit client tests are working (the Karma windows gets open) BUT integration client ones are still stuck on "loading".
This is my `.meteor/local/log/jasmine-client-integration.log`:
```
Spawn script arguments:
parentPid: 10524
command: /home/f.dasoghe/.meteor/packages/meteor-tool/.1.0.40.1ef5dzv++os.linux.x86_64+web.browser+web.cordova/meteor-tool-os.linux.x86_64/dev_bundle/bin/node
commandArguments: [ '/home/fdasoghe/devel/workspace-luna/minerva/.meteor/local/build/main.js' ]
** You've set up some data subscriptions with Meteor.publish(), but
** you still have autopublish turned on. Because autopublish is still
** on, your Meteor.publish() calls won't have much effect. All data
** will still be sent to all clients.
**
** Turn off autopublish by removing the autopublish package:
**
**   $ meteor remove autopublish
**
** .. and make sure you have Meteor.publish() and Meteor.subscribe() calls
** for each collection that you want clients to see.

[velocity] Mirror detected - Not adding velocity core
[velocity] Not adding mirror-registry because NODE_ENV is development  and IS_MIRROR is true
[velocity-mirror] Mirror is initializing...
[proxy-package-sync] Mirror detected - Not adding code
[velocity-mirror] Mirror started. Connecting via DDP to parent
[velocity] Mirror connected to parent. Registering mirror...
LISTENING
[velocity-mirror] Mirror is ready.
```
Any hint is highly appreciated...

On a side note: wouldn't it be more comfortable to revert the tests detection logic? I mean: in my project I only want to execute server unit tests, so why the Velocity report window is bloated with buttons and panels asking me about tests I don't care? In order to achieve that I have to set an environment variable (one for each type of test) but this is still cumbersome and not portable (every developer has to do that on a per-user basis). Just my 2 cents.

**Comment by Sanjo** [comment] 2015-02-06 18:36
@think01 
> integration client ones are still stuck on "loading"

Look in the browser console when you open your app if there is an error.

> In order to achieve that I have to set an environment variable (one for each type of test) but this is still cumbersome and not portable (every developer has to do that on a per-user basis). Just my 2 cents.

The option to set these settings via JavaScript in your app will be added soon. Currently you can write a run.sh script that starts you app with the correct environment variables.

**Comment by think01** [comment] 2015-02-09 15:06
In the browser console I get this (with no environment variables set):

```
 Exception in template helper: TypeError: undefined is not a function
    at http://localhost:3000/packages/velocity_html-reporter.js?a615bf3410d795106d7a78c6a94379745879f7df:651:43
    at Array.forEach (native)
    at Function._.each._.forEach (http://localhost:3000/packages/underscore.js?0a80a8623e1b40b5df5a05582f288ddd586eaa18:156:11)
    at Object.Template.velocitySummary.helpers.totalTime (http://localhost:3000/packages/velocity_html-reporter.js?a615bf3410d795106d7a78c6a94379745879f7df:649:7)
    at http://localhost:3000/packages/blaze.js?efa68f65e67544b5a05509804bf97e2c91ce75eb:2727:16
    at http://localhost:3000/packages/blaze.js?efa68f65e67544b5a05509804bf97e2c91ce75eb:1606:16
    at Spacebars.call (http://localhost:3000/packages/spacebars.js?7f53771c84a2eafac2b561c9796dda0d8af8e7f5:171:18)
    at Spacebars.mustacheImpl (http://localhost:3000/packages/spacebars.js?7f53771c84a2eafac2b561c9796dda0d8af8e7f5:108:25)
    at Object.Spacebars.mustache (http://localhost:3000/packages/spacebars.js?7f53771c84a2eafac2b561c9796dda0d8af8e7f5:112:39)
    at null._render (http://localhost:3000/packages/velocity_html-reporter.js?a615bf3410d795106d7a78c6a94379745879f7df:218:22)
meteor.js:887 Exception in template helper: TypeError: undefined is not a function
    at http://localhost:3000/packages/velocity_html-reporter.js?a615bf3410d795106d7a78c6a94379745879f7df:651:43
    at Array.forEach (native)
    at Function._.each._.forEach (http://localhost:3000/packages/underscore.js?0a80a8623e1b40b5df5a05582f288ddd586eaa18:156:11)
    at Object.Template.velocitySummary.helpers.totalTime (http://localhost:3000/packages/velocity_html-reporter.js?a615bf3410d795106d7a78c6a94379745879f7df:649:7)
    at http://localhost:3000/packages/blaze.js?efa68f65e67544b5a05509804bf97e2c91ce75eb:2727:16
    at http://localhost:3000/packages/blaze.js?efa68f65e67544b5a05509804bf97e2c91ce75eb:1606:16
    at Spacebars.call (http://localhost:3000/packages/spacebars.js?7f53771c84a2eafac2b561c9796dda0d8af8e7f5:171:18)
    at Spacebars.mustacheImpl (http://localhost:3000/packages/spacebars.js?7f53771c84a2eafac2b561c9796dda0d8af8e7f5:108:25)
    at Object.Spacebars.mustache (http://localhost:3000/packages/spacebars.js?7f53771c84a2eafac2b561c9796dda0d8af8e7f5:112:39)
    at null._render (http://localhost:3000/packages/velocity_html-reporter.js?a615bf3410d795106d7a78c6a94379745879f7df:235:24)
```
I have only server tests defined (unit and integration). It seems to me something is complaining about the missing tests and crashes, leading to the pending Velocity report.

**Comment by Sanjo** [comment] 2015-02-11 10:54
@think01 I've fixed the `Exception in template helper: TypeError: undefined is not a function` error in 0.12.3.

**Comment by think01** [comment] 2015-02-11 11:30
Thank you so much! I'll try it as soon as possible (I hope tomorrow).

**Comment by Aralun** [comment] 2015-02-12 15:30
@Sanjo Had this issue too (with total time not showing up and exceptions in console concerning `.totalTime`), fixed with an update!

**Closed** 2015-02-24 00:24 UTC
