### ISSUE TITLE
jasmine appears to break coffeescript line number reporting

### ISSUE THREAD

**Issue by nilnullzip** [Sanjo/meteor-jasmine#168] opened 2015-03-01 11:46 UTC
Normally when coffeescript reports an error, it indicates the line number in the coffeescript file. See below.

<pre>
W20150301-03:27:42.657(-8)? (STDERR) ReferenceError: xxx is not defined
W20150301-03:27:42.657(-8)? (STDERR)     at ./bar.coffee:1:1
W20150301-03:27:42.657(-8)? (STDERR)     at ./bar.coffee:1:1
W20150301-03:27:42.657(-8)? (STDERR)     at /Users/juan/Temp/programming/meteor/foo/.meteor/local/build/programs/server/boot.js:205:10
W20150301-03:27:42.657(-8)? (STDERR)     at Array.forEach (native)
W20150301-03:27:42.657(-8)? (STDERR)     at Function._.each._.forEach (/Users/juan/.meteor/packages/meteor-tool/.1.0.41.rsvhne++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
W20150301-03:27:42.657(-8)? (STDERR)     at /Users/juan/Temp/programming/meteor/foo/.meteor/local/build/programs/server/boot.js:116:5
</pre>

However, with jasmine installed, the line number given is from the compiled javascript target file. See below.

<pre>
W20150228-20:01:19.174(-8)? (STDERR) ReferenceError: xxx is not defined
W20150228-20:01:19.174(-8)? (STDERR)   at /Users/juan/Temp/programming/meteor/foo/.meteor/local/build/programs/server/app/bar.coffee.js:6:1
W20150228-20:01:19.174(-8)? (STDERR)   at /Users/juan/Temp/programming/meteor/foo/.meteor/local/build/programs/server/app/bar.coffee.js:8:3
W20150228-20:01:19.175(-8)? (STDERR)   at /Users/juan/Temp/programming/meteor/foo/.meteor/local/build/programs/server/boot.js:205:10
W20150228-20:01:19.175(-8)? (STDERR)   at Array.forEach (native)
W20150228-20:01:19.175(-8)? (STDERR)   at Function._.each._.forEach (/Users/juan/.meteor/packages/meteor-tool/.1.0.41.rsvhne++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
W20150228-20:01:19.175(-8)? (STDERR)   at /Users/juan/Temp/programming/meteor/foo/.meteor/local/build/programs/server/boot.js:116:5
</pre>

I think this may also affect breakpoints.

I tried installing mike:mocha, and no problem. I also tried installing sanjo:karma, and still no problem. So it seems related to sanjo: jasmine.

I suspect the problem is related to the .map files that map between coffeescript and target JS files. Perhaps that linkage is being disturbed?

Any ideas what could be causing this strange problem and how to work around?

**Comment by Sanjo** [comment] 2015-03-01 12:19
Cannot reproduce this. Can you create a project where I can see this please.

**Comment by nilnullzip** [comment] 2015-03-01 17:34
Thanks for the quick reply! Here you go:

> https://github.com/nilnullzip/jasmine-coffeescript-issue/

**Comment by Sanjo** [comment] 2015-03-01 18:16
Wow, the bug is strange. I have no idea why this happens. I will keep an eye open.

**Comment by nilnullzip** [comment] 2015-03-25 03:45
A little insight.

1) When the console first displays messages with filename/line numbers, it shows the .js filename that includes a long random string of digits, not the .coffee file name. Then after a few seconds, the filename changes to the much shorter coffeescript filename. It seems Chrome is fetching the .map files in the interim. So somehow that process is getting confused by something that Jasmine or Velocity is doing.

2) Actually, the bad behavior is not consistent. I have observed it sometimes displays correct line numbers, and sometimes some are correct and some are not.

3) Jasmine appears to run the browser script load twice, as I see all my load time messages printed twice. (See https://github.com/mad-eye/meteor-mocha-web/issues/140) The first time through, the line numbers are correct. It's in the second time through that they get broken. Probably we should figure out why the load script is getting run twice.

**Comment by nilnullzip** [comment] 2015-05-29 18:59
This seems to be a problem in velocity:meteor-internals package. Not specific to sanjo:jasmine. Also happens with mike:mocha. Any pointers would be appreciated.

**Comment by rissem** [comment] 2015-05-29 22:43
I've traced the problem down to https://github.com/meteor-velocity/meteor-internals/blob/develop/tools/files.js

**Comment by nilnullzip** [comment] 2015-05-29 22:51
Hey Mike, Agreed. Here's what I found:

> https://github.com/meteor-velocity/meteor-internals/issues/2

Note that I was able to improve the console line numbers by commenting out some code. But that broke debugging. Do you have any insight into what meteor-internals is doing with source maps?

**Comment by rissem** [comment] 2015-05-29 22:59
Yeah I just got to the same point. I don't have much insight into what's going on with meteor-internals or what it's doing with source maps. I might take a look later this weekend if @Sanjo doesn't beat me to the punch.

**Comment by Sanjo** [comment] 2015-05-29 23:01
Closing this one in favor of https://github.com/meteor-velocity/meteor-internals/issues/2.

**Closed by Sanjo** 2015-05-29 23:01 UTC
Labels: bug
